################################################################################
# Azure App Service Configuration
# This file defines the deployment configuration for Azure App Service
# 
# Generated for: Adal Naga Ordinances Chatbot
# Stack: Python 3.12 with Flask + Gunicorn
################################################################################

trigger:
  - main
  - deploy

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: '$(REGISTRY_NAME)'
  imageRepository: 'adal-naga-ordinances'
  containerRegistry: '$(REGISTRY_LOGIN_SERVER)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  imageName: '$(containerRegistry)/$(imageRepository):$(tag)'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildImage
        displayName: Build Docker Image
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: Push an image to registry
            inputs:
              command: push
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployToAzure
        displayName: Deploy to Azure App Service
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: Deploy to Azure App Service
                  inputs:
                    azureSubscription: '$(AZURE_SUBSCRIPTION)'
                    appName: '$(APP_SERVICE_NAME)'
                    containers: |
                      $(imageName)
                    multipleContainers: false
                    imagePullPolicy: 'Always'
